#!/bin/sh
# This file is part of InfoGrid(tm). You may not use this file except in
# compliance with the InfoGrid license. The InfoGrid license and important
# disclaimers are contained in the file LICENSE.InfoGrid.txt that you should
# have received with InfoGrid. If you have not received LICENSE.InfoGrid.txt
# or you do not consent to all aspects of the license and the disclaimers,
# no license is granted; do not use this file.
#
# For more information about InfoGrid go to http://infogrid.org/
#
# Copyright 1998-2008 by R-Objects Inc. dba NetMesh Inc., Johannes Ernst
# All rights reserved.
#
# (end of header)
#
# prerm script for InfoGrid Debian package
# This was inspired by the corresponding script in the tomcatXX-webapps module.

set -e

case "$1" in
    remove|deconfigure)
        if [ -x /etc/init.d/tomcat5.5 ]; then
            if invoke-rc.d tomcat5.5 status >/dev/null; then
                invoke-rc.d tomcat5.5 force-reload || true
            if
        if
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0;
